#yml形式的
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false  #这个是关闭thymeleaf缓存
    enabled: false #关闭thymeleaf模板　
  datasource:
    url: jdbc:sqlite::resource:db/demo.db
    driverClassName: org.sqlite.JDBC
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/jesdev?characterEncoding=utf-8
#    driverClassName: com.mysql.jdbc.Driver
#    username: wind
#    password: wind
  jpa:
##    database: mysql
    database-platform: com.mindata.blockchain.core.sqlite.SQLiteDialect
    show-sql: true
    generate-ddl: true
server:
  tomcat:
    uri-encoding: utf-8
  port: 8088
  servlet:
    context-path: /demo
    encoding:
      force: true
      charset: utf-8
      enabled: true
debug: true
